import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Contact from "@/components/Contact";
import Join from "@/components/Join";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" /> */}
        {/* <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
          AOS.init();
        </script> */}

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Kalnia:wght@100..700&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>



        <Navbar></Navbar>
        {children}
        <Contact></Contact>
        <Join></Join>
      </body>
    </html>
  );
}
