import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Contact from "@/components/Contact";
import Join from "@/components/Join";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
          AOS.init();
        </script>

    

        <Navbar></Navbar>
        {children}
        <Contact></Contact>
        <Join></Join>
      </body>
    </html>
  );
}
